### PR TITLE
EOS-19784: About section showing forbidden error to CSM Manage and Mo…

### PR DESCRIPTION
**Pull request by SrikantVishwakarma**
# Backend

## Problem Statement
<pre>
Story Ref (if any): https://jts.seagate.com/browse/EOS-19784
</pre>
## Unit testing on RPM done
<pre>
Yes
</pre>
## Problem Description
<pre>
About section showing forbidden error to CSM Manage and Monitor users for details api.
</pre>
## Solution
<pre>
Added security read permission to Manage and Monitor users.
</pre>
## Unit Test Cases
<pre>
Yes
</pre>
Signed-off-by: Signed-off-by: SrikantVishwakarma <srikant.vishwakarma@seagate.com>

### CODE REVIEW

**Comment by cortx-admin** [comment]
Can one of the admins verify this patch?

**Review by soniyamoholkar — APPROVED** [review]

**Review by pawankumarsrivastava — APPROVED** [review]

**Comment by SrikantVishwakarma** [comment]
about_fix1
about_fix2

**Comment by SrikantVishwakarma** [comment]
Mini-provisioning and VM deployment log files:
[cortx_deployment_EOS-19784.log](https://github.com/Seagate/cortx-manager/files/6421713/cortx_deployment_EOS-19784.log)
[mini_pro_ EOS-19784.log](https://github.com/Seagate/cortx-manager/files/6421715/mini_pro_.EOS-19784.log)

**Comment by SrikantVishwakarma** [comment]
mini_pro_EOS-19784

**Review by kupranay — APPROVED** [review]

**Pull request merged**
