### PR TITLE
EOS-18534: 3node miniprovisioing modifications: Postinstall, Prepare, Config, Init

### PR DESCRIPTION
**Pull request by udayan-y21**
# Backend

## Problem Statement
<pre>
Story Ref (if any): https://jts.seagate.com/browse/EOS-18534
</pre>
## Unit testing on RPM done
<pre>
Yes
</pre>
## Problem Description
<pre>
As per new design for 3Node mini provisioning, modifications required in csm_setup commands
</pre>
## Solution
<pre>
Modifications is done for 3node mini provisioning. 
Prepare phase is added to csm_setup
Validators are intoduced for validate confstorekeys, validate services etc
</pre>
## Unit Test Cases

image

image
image
image
image

Signed-off-by:

### CODE REVIEW

**Comment by kupranay** [comment]
run mini-provisioning

**Comment by kupranay** [comment]
run mini-provisioning

**Comment by kupranay** [comment]
run mini-provisioning

**Comment by kupranay** [comment]
http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Mini-Provisioning/job/cortx-manager/203/
request passes hence merging

**Review by pawankumarsrivastava — APPROVED** [review]

**Pull request merged**
