### PR TITLE
Audit log fix for msg field

### PR DESCRIPTION
**Pull request by soniyamoholkar**
# Backend

## Problem Statement
<pre>
Story Ref (if any): msg rough field error is coming.
</pre>
## Unit testing on RPM done
<pre>
Yes
</pre>
## Problem Description
<pre>
The are some old logs which are not inserted in required json format. which leads to the error and does not display the audit logs.
</pre>
## Solution
<pre>
1. msg field is added in CSMAuditLog Model
2. added default values for all the fields
</pre>
## Unit Test Cases
<pre>
1. Tested by doing S3 operations from UI as well as CLI
2. Tested with Alerts, stats from UI
3. Tested view logs for seven days
4. Tested with downloading audit logs for seven days.
image

</pre>
Signed-off-by: Soniya Moholkar <soniya.moholkar@seagate.com>

### CODE REVIEW

**Review by kupranay — APPROVED** [review]

**Review by udayan-y21 — APPROVED** [review]

**Review by pawankumarsrivastava — APPROVED** [review]

**Review by kupranay — APPROVED** [review]

**Comment by kupranay** [comment]
ok to test

**Comment by kupranay** [comment]
run vm-deployment

**Comment by kupranay** [comment]
run mini-provisioning"

**Comment by kupranay** [comment]
Looks like intermittent failure, VM deployment is getting success hence merging

**Pull request merged**
