### PR TITLE
EOS-15616:Alerts.json is present outside alerts directory after creating support bundle

### PR DESCRIPTION
**Pull request by rohitkolapkar**
# Backend

## Problem Statement
<pre>
Story Ref (if any):
</pre>
[EOS-15616](https://jts.seagate.com/browse/EOS-15616)
## Unit testing on RPM done
<pre>
No
</pre>
## Problem Description
<pre>
Alerts.json is present outside alerts directory after creating support bundle
</pre>
## Solution
<pre>
Code changes done for deletion of Alerts.json file present outside the Alert directory after Support Bundle tar generation.
</pre>
## Unit Test Cases
<pre>
1. cortxcli support_bundle generate "Test 1" -c all

1_Generate Support bundle

2. Navigate to symlink path, Untar the generated support bundle and fire ls and observe,
**alert.json should not be present outside alerts directory.**

2_Untar the generated support bundle

3. Go to alerts directory and Untar the alert support bundle tar file, fire ls.

3_Untar the generated support bundle for alerts
4_tree for support bundle directory

</pre>
Signed-off-by: rohitkolapkar <rohit.j.kolapkar@seagate.com>

### CODE REVIEW

**Comment by cortx-admin** [comment]
Can one of the admins verify this patch?

**Review by udayan-y21 — APPROVED** [review]

**Review by pawankumarsrivastava — APPROVED** [review]

**Comment by kupranay** [comment]
ok to test

**Comment by kupranay** [comment]
add to allowlist

**Comment by kupranay** [comment]
run mini-provisioning

**Comment by rohitkolapkar** [comment]
Mini Provisioning is failing due to decryption issue. Script is still trying to decrypt with older key.
image

**Comment by rohitkolapkar** [comment]
RPM build is successful. Logs attached.
[console output.txt](https://github.com/Seagate/cortx-manager/files/6345021/console.output.txt)

**Comment by kupranay** [comment]
ok to test

**Review by kupranay — APPROVED** [review]

**Pull request merged**
