### PR TITLE
EOS-19358:Changes for s3 account delete issue

### PR DESCRIPTION
**Pull request by rohitkolapkar**
# Backend

## Problem Statement
<pre>
Story Ref (if any):
</pre>
[EOS-19157](https://jts.seagate.com/browse/EOS-19157)
[EOS-19358](https://jts.seagate.com/browse/EOS-19358)
[EOS-19733](https://jts.seagate.com/browse/EOS-19733)

## Unit testing on RPM done
<pre>
No
</pre>
## Problem Description
<pre>
After login to cortx-manager (and also on cortxcli) with s3 account, user is able to delete s3 account but getting 
500, 'S3AccountsView' has no attribute _cleanup_sessions as 
error code and error response respectively. 

</pre>
## Solution
<pre>
Added definition for _cleanup_sessions in S3AccountsView on backend.
</pre>
## Unit Test Cases
<pre>
1. On Gui
s3account delete

s3account delete_2

2. On Cortxcli:
- Login using CSM admin, List down S3 acoounts
1_login_as_admin

- Login using S3 account on CLI, delete the s3 user and observe. S3 user should get deleted without error message.
s3account delete on cortxcli

- Login using CSM admin and crosscheck if S3 account got delete.
2_login_as_admin

</pre>
Signed-off-by: rohitkolapkar <rohit.j.kolapkar@seagate.com>

### CODE REVIEW

**Review by kupranay — APPROVED** [review]

**Review by pawankumarsrivastava — APPROVED** [review]

**Review by soniyamoholkar — APPROVED** [review]

**Comment by kupranay** [comment]
ok to test

**Comment by kupranay** [comment]
run mini-provisioning

**Comment by kupranay** [comment]
@rohitkolapkar  please test it from GUI and CLI and update

**Comment by rohitkolapkar** [comment]
Okay, on it. @kupranay

**Comment by rohitkolapkar** [comment]
I tested it on GUI and CLI both, it is working as expected. Also updated the PR template. @kupranay

**Comment by kupranay** [comment]
add to allowlist

**Comment by kupranay** [comment]
run mini-provisioning

**Comment by kupranay** [comment]
ok to test

**Pull request merged**
