### PR TITLE
Moving ryslog config to post install

### PR DESCRIPTION
**Pull request by udayan-y21**
# Backend

## Problem Statement
<pre>
Story Ref (if any):
</pre>
## Unit testing on RPM done
<pre>
No
</pre>
## Problem Description
<pre>

</pre>
## Solution
<pre>
As per the latest discussion over rsyslog configuration,  decision is made that rsyslog configuration for csm will be moved in post-install
</pre>
## Unit Test Cases
<pre>

</pre>
Signed-off-by:

### CODE REVIEW

**Review by pawankumarsrivastava — APPROVED** [review]

**Review by kupranay — APPROVED** [review]

**Comment by kupranay** [comment]
run mini-provisioning

**Comment by kupranay** [comment]
run vm-deployment

**Comment by kupranay** [comment]
ok to test

**Comment by kupranay** [comment]
ok to test

**Comment by kupranay** [comment]
ok to test

**Pull request merged**
