### PR TITLE
Adding "cortxcli security"  for displaying SSL certificate data.

### PR DESCRIPTION
**Pull request by udayan-y21**
# CLI

## Problem Statement
<pre>
Story Ref (if any): https://jts.seagate.com/browse/EOS-17017
</pre>
## Unit testing on RPM done
<pre>
Yes
</pre>
## Problem Description
<pre>
SSL certificate information required to be dispplayed in CLI.
</pre>
## Solution
<pre>
"cortxcli security details" comand created to display system's SSL certificate Information. 
For this pupose is created for "tls/bundle/details" is integrated into cortxcli.
</pre>
## CLI Document Updated 
* [File Link](https://seagatetechnology-my.sharepoint.com/:x:/g/personal/prathamesh_rodi_seagate_com/EVRDDBTuaF5EvabmU3XDWOIBCm6NhIPpYo1ShcnAXUFzag?e=XfH7F2)
## Unit Test Cases
```
**cortxcli$ -h**
usage: cortxcli [-h]
                {'alerts', 'security', 'system', 's3accounts',
                'support_bundle', 'users'} ...

Cortx cli commands

positional arguments:
  {'alerts', 'security', 'system', 's3accounts', 'support_bundle', 'users'}

optional arguments:
  -h, --help  show this help message and exit
cortxcli$ security -h
usage: cortxcli security [-h] {details} ...

positional arguments:
  {details}
    details   Displays SSL Certificate Information.

optional arguments:
  -h, --help  show this help message and exit
```
**cortxcli$ security details**
```json
{
    "cert_details": {
        "issuer": {
            "commonName": "CSM",
            "countryName": "US",
            "emailAddress": "csm_root_ca@mail.com",
            "localityName": "Voronezh",
            "organizationName": "Seagate",
            "organizationalUnitName": "CSM",
            "stateOrProvinceName": "Colorado"
        },
        "not_valid_after": "2033-10-14 16:29:14",
        "not_valid_before": "2020-02-05 16:29:14",
        "serial_number": 17098183298577567507,
        "subject": {
            "commonName": "localhost",
            "countryName": "US",
            "localityName": "Denver",
            "organizationName": "Seagate",
            "organizationalUnitName": "CSM",
            "stateOrProvinceName": "Colorado"
        },
        "version": "Version.v1"
    }
}
```
**cortxcli$ security details -f xml**
```xml
<cert_details>

  <issuer>
    <commonName>CSM</commonName>
    <countryName>US</countryName>
    <emailAddress>csm_root_ca@mail.com</emailAddress>
    <localityName>Voronezh</localityName>
    <organizationName>Seagate</organizationName>
    <organizationalUnitName>CSM</organizationalUnitName>
    <stateOrProvinceName>Colorado</stateOrProvinceName>
  </issuer>
  <not_valid_after>2033-10-14 16:29:14</not_valid_after>
  <not_valid_before>2020-02-05 16:29:14</not_valid_before>
  <serial_number>17098183298577567507</serial_number>
  <subject>
    <commonName>localhost</commonName>
    <countryName>US</countryName>
    <localityName>Denver</localityName>
    <organizationName>Seagate</organizationName>
    <organizationalUnitName>CSM</organizationalUnitName>
    <stateOrProvinceName>Colorado</stateOrProvinceName>
  </subject>
  <version>Version.v1</version>
</cert_details>
```

Signed-off-by:  Udayan Yaragattikar (udayan.yaragattikar@seagate.com)

### CODE REVIEW

**Comment by prathameshrodi** [comment]
Hi @udayan-y21  Can we make changes to Output Table Method to Display this JSON in Table Format ??

**Comment by udayan-y21** [comment]
> Hi @udayan-y21 Can we make changes to Output Table Method to Display this JSON in Table Format ??

@kupranay  As this command has only single json output. Also this output structure will be constant everytime for the pem file. There is no multiple json objects to show in tabular format. 
API output has nested json object. Also number of json attributes (keys) may vary as per the information present in ssl(.pem) file. To more attributes that may found in ssl file can be seen this link https://cryptography.io/en/2.7/x509/reference/?highlight=NameOID#cryptography.x509.oid.NameOID.

Our current cli output class doesnt supports nested  json format. So to integrate the nested json to cli output method will require more time for implementation and testing. 
Please let me know how to proceed?

**Comment by kupranay** [comment]
> > Hi @udayan-y21 Can we make changes to Output Table Method to Display this JSON in Table Format ??
> 
> @kupranay As this command has only single json output. Also this output structure will be constant everytime for the pem file. There is no multiple json objects to show in tabular format.
> API output has nested json object. Also number of json attributes (keys) may vary as per the information present in ssl(.pem) file. To more attributes that may found in ssl file can be seen this link https://cryptography.io/en/2.7/x509/reference/?highlight=NameOID#cryptography.x509.oid.NameOID.
> 
> Our current cli output class doesnt supports nested json format. So to integrate the nested json to cli output method will require more time for implementation and testing.
> Please let me know how to proceed?

JSON is a program readable format, but not a user eadable format. we should show it in either a list or a table. Showing JSON is not a good idea at all

**Comment by udayan-y21** [comment]
> > > Hi @udayan-y21 Can we make changes to Output Table Method to Display this JSON in Table Format ??
> > 
> > 
> > @kupranay As this command has only single json output. Also this output structure will be constant everytime for the pem file. There is no multiple json objects to show in tabular format.
> > API output has nested json object. Also number of json attributes (keys) may vary as per the information present in ssl(.pem) file. To more attributes that may found in ssl file can be seen this link https://cryptography.io/en/2.7/x509/reference/?highlight=NameOID#cryptography.x509.oid.NameOID.
> > Our current cli output class doesnt supports nested json format. So to integrate the nested json to cli output method will require more time for implementation and testing.
> > Please let me know how to proceed?
> 
> JSON is a program readable format, but not a user eadable format. we should show it in either a list or a table. Showing JSON is not a good idea at all

@kupranay  As per discusion,

Output of the command is in json and xml format where as tabular format is not in the option. API response api/v1/tls/bundle/details has multi level json format which is not currently supported by Output class of cli. 

Implementation of multi level json into tabular format is bit complex and considering the time constraint of the sprint and also scope of the current story, this implementation will to be taken in future sprint.

CC: @pawankumarsrivastava

**Review by prathameshrodi — APPROVED** [review]

**Review by pawankumarsrivastava — APPROVED** [review]

**Pull request merged**
