### PR TITLE
EOS-22625: CSM Setup for PAM config

### PR DESCRIPTION
**Pull request by rohitkolapkar**
Signed-off-by: rohitkolapkar <rohit.j.kolapkar@seagate.com>

# Backend

# Problem Statement
JIRA ticket: [EOS-22625](https://jts.seagate.com/browse/EOS-22625)
This Patch will configure CORTX-PAM Module on cortx deployed VM.

## Design
To configure CORTX-PAM module, below steps are involved. 
1. PAM dependencies installation --> build.sh
2. Compilation and .so file creation from pam_cortx.c --> build.sh
2. Copying pam_cortx.so to /lib64/security/ --> csm_setup config phase.
3. Configuration changes in /etc/pam.d/password-auth-ac  --> csm_setup config phase.

## Coding

- _Coding conventions are followed and code is consistent. Yes/No?_ Yes
- _Confirm All CODACY errors are resolved. Yes/No?_ 

## Testing

- _Confirm that Test Cases are added (for both the cases, fix and feature). Yes/No?_
- _Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability. Yes/No?_
- _Confirm Testing was performed with installed RPM. Yes/No?_ Yes
- _Confirm all the ut/regression/smoke test has been performed [Y/N]_ Yes

1. Dependencies installation.
image

2. PAM module compilation and .so creation
http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/cortx-manager/650/console

image

3. csm_setup post_install, prepare, config, init
image

4. is pam_cortx.so present at /lib64/security/  after csm_setup config PASS ?
image

5. configuration changes in /etc/pam.d/password-auth-ac after  csm_setup config PASS ?
image

6. csm_setup cleanup
image

## Checklist

- _PR is self-reviewed? Yes/No?_ Yes
- _GitHub Issue is updated_ Yes
- _Jira is updated_ Yes
  -  _Check if the description is clear and explained._ 
    -  _Check Acceptance Criterion is defined._
      -  _All the tests performed should be mentioned before Resolving a JIRA._
        -  _Verification needs to be done before marked as Closed/Verified_
        - _Any interface change Yes/No?_ No
        - _Change notified to other gatekeepers: Yes/No?_ NA
        - _Code reviews done and addressed: Yes/No?_
        - _Codacy issues reviewed and addressed: Yes/No?_
        - _Deployment test : Done/Not?_ Done
        - _UT/smoke test: Done/Not?_ 
        - _Jira number added to PR: Yes/No?_ Yes
        - _Github merge done using UI: Yes/No?_
        - _Side effects on other features - deployment/update/node-replacement_
        - _Changes to quick-start-guide/community impact_
        - _All dependent component code PR are raised or already merged Yes/No_
        - _All dependent code already merged in landing branch Yes/No_

-----
[View rendered csm/cortx-pam/readme.md](https://github.com/rohitkolapkar/cortx-manager/blob/EOS-22625-csm-setup-pam/csm/cortx-pam/readme.md)

### CODE REVIEW

**Comment by rohitkolapkar** [comment]
CSM agent RPM build job: http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/cortx-manager/650/ 

RPM location: http://cortx-storage.colo.seagate.com/releases/eos/components/dev/multibranch/cortx-manager/EOS-22625-csm-setup-pam/

**Comment by rohitkolapkar** [comment]
Custom ci Job - http://eos-jenkins.mero.colo.seagate.com/job/GitHub-custom-ci-builds/job/centos-7.8/job/cortx-custom-ci/2256/ - green.
Artifact location: http://cortx-storage.colo.seagate.com/releases/cortx/github/integration-custom-ci/centos-7.8.2003/custom-build-2256/

**Review by pawankumarsrivastava — APPROVED** [review]

**Comment by pawankumarsrivastava** [comment]
@udayan-y21 Please verify

**Comment by rohitkolapkar** [comment]
Cortx stack deployment on VM with custom ci build : http://eos-jenkins.colo.seagate.com/job/Cortx-Deployment/job/VM-Deployment-R2-1Node/1638/

**Review by udayan-y21 — APPROVED** [review]

**Pull request merged**
