### PR TITLE
CORTX-31950: connect to RGW via HTTPS

### PR DESCRIPTION
**Pull request by avrnv**
# Pull Request
## Problem Statement
-   [CORTX-31950](https://jts.seagate.com/browse/CORTX-31950): CSM-S3 communication should be on https.

## Design
-   Select HTTPS endpoint from the list of mini-provisioned endpoints.
-   Pass URL as it is to the S3 cilent.
- NOTE: This PR depends on https://github.com/Seagate/cortx-utils/pull/824. Please, merge cortx-utils fix first.

# Custom Build with dependent branch
- [Custom Build Job](https://eos-jenkins.colo.seagate.com/job/GitHub-custom-ci-builds/job/generic/job/custom-ci/6649/)
- Custom Build for deployment
cortx-docker.colo.seagate.com/seagate/cortx-control:2.0.0-6649-custom-ci
cortx-docker.colo.seagate.com/seagate/cortx-data:2.0.0-6649-custom-ci
cortx-docker.colo.seagate.com/seagate/cortx-control:2.0.0-6649-custom-ci

- [Deployment Job](https://eos-jenkins.colo.seagate.com/job/Cortx-Automation/job/RGW/job/setup-cortx-rgw-cluster/6653/)
- 1Node deployed VM
image

-   \[x\] Coding conventions are followed and code is consistent

-   \[ \] Unit and System Tests are added
-   \[x\] Test Cases cover Happy Path, Non-Happy Path and Scalability
-   \[x\] Testing was performed with RPM

-   \[ \] Interface change (if any) are documented
-   \[ \] Side effects on other features (deployment/upgrade)
-   \[ \] Dependencies on other component(s)

-   \[x\] JIRA number/GitHub Issue added to PR
-   \[x\] PR is self reviewed
-   \[x\] Jira and state/status is updated and JIRA is updated with PR link
-   \[x\] Check if the description is clear and explained

-   \[ \] Changes done to WIKI / Confluence page / Quick Start Guide

### CODE REVIEW

**Comment by shailesh-vaidya** [comment]
retest this please

**Review by rohitkolapkar — APPROVED** [review]

**Comment by rohitkolapkar** [comment]
Please attach some dev testing screenshots. eg. IAM operations.

**Comment by avrnv** [comment]
Create IAM user successful execution
```
+ BEARER='Authorization: Bearer bd66b57f9953457898b7260ecd89f2de'
+ ENDPOINT=api/v2/iam/users
+ PAYLOAD='{"uid": "testuser", "display_name":"Test user"}'
+ echo Authorization: Bearer bd66b57f9953457898b7260ecd89f2de
Authorization: Bearer bd66b57f9953457898b7260ecd89f2de
+ curl -k -X POST -H 'Content-type: applicaiton/json' -H 'Authorization: Bearer bd66b57f9953457898b7260ecd89f2de' -d '{"uid": "testuser", "display_name":"Test user"}' https://ssc-vm-g2-rhev4-3078.colo.seagate.com:31169/api/v2/iam/users
{"tenant": "", "user_id": "testuser", "display_name": "Test user", "email": "", "suspended": 0, "max_buckets": 1000, "subusers": [], "keys": [{"user": "testuser", "access_key": "XFMENA45TFK357ER902N", "secret_key": "n1JPl5DCRBaR4pdCDReLGtGrf19BAdLDsaMe5DEv"}], "swift_keys": [], "caps": [], "op_mask": "read, write, delete", "system": "false", "admin": "false", "default_placement": "", "default_storage_class": "", "placement_tags": [], "bucket_quota": {"enabled": false, "check_on_raw": false, "max_size": -1, "max_size_kb": 0, "max_objects": -1}, "user_quota": {"enabled": false, "check_on_raw": false, "max_size": -1, "max_size_kb": 0, "max_objects": -1}, "temp_url_keys": [], "type": "rgw", "mfa_ids": []}
```

**Review by pawankumarsrivastava — APPROVED** [review]

**Comment by kupranay** [comment]
ok to test

**Pull request merged**
